# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Driver
version:      0.005
version_from: lib/Class/Driver.pm
installdirs:  site
requires:
    Class::Clone:                  0.05
    Sub::Uplevel:                  0.06
    Symbol::Table:                 1.01
    Test::Exception:               0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
