# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Driver
version:      0.001
version_from: lib/Class/Driver.pm
installdirs:  site
requires:
    B::Deparse:                    0.59
    Class::Clone:                  0.02
    Symbol::Table:                 1.01
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
